# use official Python image with size around 200 MB
FROM python:3.11-slim

# install system dependencies first for PyQt and X11 with size around 300 MB
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    libx11-xcb1 \
    libxrender1 \
    libxcb1 \
    libxcb-render0 \
    libxcb-shape0 \
    libxcb-shm0 \
    libxcb-xfixes0 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-randr0 \
    libxcb-render-util0 \
    libxcb-xinerama0 \
    libxcb-cursor0 \
    libxkbcommon-x11-0 \
    libegl1 \
    libgl1 \
    libglib2.0-0 \
    libxext6 \
    libsm6 \
    libice6 \
    libdbus-1-3 \
    xauth \
    xvfb \
    x11-utils \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# set working directory inside container
WORKDIR /app

COPY requirements.txt ./

# install dependencies with size around 1.3 GB
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir pytest pytest-qt

# copy all files to container
COPY . .

# set python env path
ENV PYTHONPATH=/app

RUN chmod +x ./entrypoint.sh
# run the tests with virtual display
CMD ["./entrypoint.sh"]
